### ISSUE TITLE
başlıklardaki ı harfi kayboluyor

### ISSUE THREAD

**Issue by co3moz** [sausozluk/web#6]
- Gemi biraz sola mı çekiyor kuna?
- Ne gemisi abi
- Abi mi?

**Comment by okan** [comment]
@erayarslan bize bilgi böyle geliyor 😌

**Comment by erayarslan** [comment]
eklediğim topic regex indendir. düzeltiyorum.

**Comment by erayarslan** [comment]
[done](http://beta.sausozluk.org/oliyi--118)
