### ISSUE TITLE
büyük küçük harfli bkz

### ISSUE THREAD

**Issue by onurtnrkl** [sausozluk/web#68]
bkz oluşturulurken string değerinin küçük harfe dönüştürülmesi(compose.js) veya aratılırken küçük harfli başlık sonucuna gitmesi sorunu çözebilir.

`if (value) {
          utils.insertAtCaret('new_entry', '(bkz: ' + value.toLowerCase() + ')');
        }`

**Comment by erayarslan** [comment]
tamamdır kanka, yazdım bi kenara.

**Comment by erayarslan** [comment]
Fixed. #f869da3fb7a49da3deafe485a8f06455db0e9737
