### ISSUE TITLE
başlıktaki son entryi sildikten sonra yönlendirme

### ISSUE THREAD

**Issue by okan** [sausozluk/web#9]
başlıktaki son entryi sildikten sonra başlığı da uçuruyoruz. fakat client tarafında herhangi bir yönlendirme olmadığı için mevcut ekranda yeniden entry girmeye çalışınca (başlık uçurulduğu için) sorun oluyor. yönlendirme yapsak iyi olur.

**Comment by erayarslan** [comment]
son entry i sildiğimi anlayabilirim sanırım bi şey döndürmeden.
direk view üzerinde takla atarak.

> son entry silindikten sonra ana sayfaya yönlendiriyorum.

**Comment by erayarslan** [comment]
[done](https://github.com/sausozluk/web/commit/9238a3033c1394ad277af44c6bf6162a8e8bde7d)

**Comment by okan** [comment]
aynı olan tekil entry için de geçerli :D

**Comment by erayarslan** [comment]
[done pt2](https://github.com/sausozluk/web/commit/b22c2d89b0aba00f2ff050e7d41fcdb51835ffaa) 🐹
